### ISSUE TITLE
How to integrate zulip into react application? 

### ISSUE THREAD

**Issue by riyasi2i** [zulip/zulip-js#105]
Is zulip support to add their feature to react app using their rest API? how the mention will work while sending message using rest api?

**Comment by marqpdx** [comment]
hello @riyasi2i 
have you made progress on this? i think it's a great idea, too!
thanks,
m

**Comment by klauss194** [comment]
+1

**Comment by riyasi2i** [comment]
Hi, @marqpdx  
I have tried this without backend, I can able to send personal/channel message via bot but not able to send individual text to particular user/channel so we dropped this and build own chat applications using socket.io

Document which i referred 
https://zulip.com/api/send-message
