### ISSUE TITLE
Add  Support For  Create Stream

### ISSUE THREAD

**Issue by vikashsingh005** [zulip/zulip-js#14]
Currenlty  we  have  pythons   Api  https://github.com/zulip/zulip/blob/master/tools/lib/api_tests.py#L7

which  will  addSubscription  where  it  will  create  stream,

how  we  able  to  do  same  thing  using  javascript

**Comment by timabbott** [comment]
Hi @vikashsingh005!  Sorry for the slow reply.  @aero31aero @arpith do either of you have time to help with this?  I think it should be fairly easy to add.

**Comment by arpith** [comment]
Not really! Happy to review / give feedback :)

**Comment by aero31aero** [comment]
@zulipbot claim
I'm kind of free. I'll give this a try.

**Comment by synicalsyntax** [comment]
@timabbott zulipbot couldn't assign to this issue; did you give it write access to this repo?

**Comment by timabbott** [comment]
Fixed.

**Comment by aero31aero** [comment]
@zulipbot claim
This should work now.
