### ISSUE TITLE
Export zulip-js/src/api.js:api as call_endpoint.

### ISSUE THREAD

**Issue by eeshangarg** [zulip/zulip-js#21]
In our Python API, we have [call_endpoint](https://github.com/zulip/python-zulip-api/blob/master/zulip/zulip/__init__.py#L570), which is a function that allows one to interface with the API on a lower level than some of the more higher-level functions such as `send_message`. In JavaScript, we have the [api function](https://github.com/zulip/zulip-js/blob/master/src/api.js#L4), but it isn't exported as part of the `zulip-js` module.

We should export it as `call_endpoint` for consistency between our Python and JavaScript APIs so that we can write JavaScript code examples in our API docs for when there isn't a specific function for a specific endpoint.

@aero31aero: FYI :)

**Comment by aero31aero** [comment]
@zulipbot claim
