### ISSUE TITLE
Add a renderMessage function.

### ISSUE THREAD

**Issue by eeshangarg** [zulip/zulip-js#22]
We should add a similar function such as [render_message](https://github.com/zulip/python-zulip-api/blob/master/zulip/zulip/__init__.py#L851) in our Python API to [this file](https://github.com/zulip/zulip-js/blob/master/src/resources/messages.js).

This is a part of our goal to try and reconcile our JavaScript and Python API and document both exhaustively. See zulip/zulip#7860 and zulip/zulip#7947. :)

@aero31aero FYI

**Comment by aero31aero** [comment]
@zulipbot claim
