### ISSUE TITLE
Add `params` parameter to streams.retrieve.

### ISSUE THREAD

**Issue by eeshangarg** [zulip/zulip-js#23]
We should add a `params` parameter to [streams.retrieve](https://github.com/zulip/zulip-js/blob/master/src/resources/streams.js). This will allow us to pass in arguments such as `include_public`, `include_all_active`, etc. to the API call (see [here](https://github.com/zulip/zulip/blob/master/zerver/views/streams.py#L423)).

For more information on what I mean about `params`, see [this](https://github.com/zulip/zulip-js/blob/master/src/resources/users.js#L5). :)

@aero31aero: FYI :)

**Comment by Balaji2198** [comment]
@zulipbot  claim.
