### ISSUE TITLE
users: Add getProfile method.

### ISSUE THREAD

**Issue by eeshangarg** [zulip/zulip-js#32]
We should add a `getProfile` method to [users.js](https://github.com/zulip/zulip-js/blob/master/src/resources/users.js) that allows one to get the profile of the user/bot that requests the `GET /api/v1/users/me` endpoint, similar to [the `get_profile` method](https://github.com/zulip/python-zulip-api/blob/master/zulip/zulip/__init__.py#L735) in our Python API.

@aero31aero: FYI

Also, see, zulip/zulip#7994.

**Comment by Balaji2198** [comment]
@aero31aero  Shall I work on this?

**Comment by aero31aero** [comment]
Sure @Balaji2198 . Thanks!
