### ISSUE TITLE
Fix examples in Readme.md

### ISSUE THREAD

**Issue by Milind712000** [zulip/zulip-js#77]
The examples in readme have minor errors such as 
- missing brackets 
- using zulip.streams.subscriptions() instead of zulip.streams.subscriptions.retrieve()  

Also the example in file https://github.com/zulip/zulip-js/blob/master/examples/subscriptions.js is wrong
 
should I send a PR to fix these

**Comment by aero31aero** [comment]
Hey, yes, we'd be very happy to have a PR fixing these. :)
