### ISSUE TITLE
Add support for reading configuration from a zuliprc file

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-js#8]
Given our plans with https://github.com/zulip/zulip/issues/2327, it probably make sense to have the javascript client support reading zuliprc files.

**Comment by CestDiego** [comment]
I'm interested in helping here, is there a sample `.zuliprc` file somewhere?

**Comment by timabbott** [comment]
@CestDiego https://chat.zulip.org/api/ explains the format

@arpith it looks like you implemented this in #10; did we not get around to merging + releasing it?

**Comment by arpith** [comment]
Merged and released :)
